### ISSUE TITLE
Possible race condition with `jsonResponse` use

### ISSUE THREAD

**Issue by alob-mtc** [neymarjimoh/fincra-go#18]
https://github.com/neymarjimoh/fincra-go/blob/9eecbd41aa04cdca0c4937e003319b70f2309f9b/client.go#L66
`jsonResponse` is declared as a global variable and reused multiple times in the code, this can trigger possible race conditions when lib functions are called in multiple goroutines

**Comment by neymarjimoh** [comment]
> https://github.com/neymarjimoh/fincra-go/blob/9eecbd41aa04cdca0c4937e003319b70f2309f9b/client.go#L66
> 
> 
> `jsonResponse` is declared as a global variable and reused multiple times in the code, this can trigger possible race conditions when lib functions are called in multiple goroutines

Thanks for bringing up this concern. I've made some adjustments to address the potential race condition with `jsonResponse`. Instead of using a global variable, I've modified the `sendRequest` function to return the `jsonResponse` to the calling function. This should help avoid race conditions when multiple goroutines are involved.

Please feel free to review the changes, and if you have any further suggestions or concerns, I'm open to feedback.
